
volumes:
  mg_lib1:
  mg_log1:
  mg_etc1:
  mg_lib2:
  mg_log2:
  mg_etc2:
  mg_lib3:
  mg_log3:
  mg_etc3:

services:

  mage_p:
    image: memgraph/memgraph-mage:latest
    environment:
      - MEMGRAPH_MANAGEMENT_PORT=13011
      - MEMGRAPH_USER=user
      - MEMGRAPH_PASSWORD=user
    ports:
      - "7687:7687"  # Bolt protocol
      - "13011:13011"  # Management port
    volumes:
      - ./init_primary.cypherl:/tmp/init/init.cypherl:ro
      - mg_lib1:/var/lib/memgraph
      - mg_log1:/var/log/memgraph
    command: ["--init-file=/tmp/init/init.cypherl", "--data-recovery-on-startup=true"]
    healthcheck:
      test: ["CMD-SHELL", "echo 'RETURN 0;' | mgconsole || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s

  mage_s1:
    image: memgraph/memgraph-mage:latest
    environment:
      - MEMGRAPH_MANAGEMENT_PORT=13011
      - MEMGRAPH_USER=user
      - MEMGRAPH_PASSWORD=user
    ports:
      - "7688:7687"  # Bolt protocol
      - "13012:13011"  # Management port
    volumes:
      - ./init_secondary.cypherl:/tmp/init/init.cypherl:ro
      - mg_lib2:/var/lib/memgraph
      - mg_log2:/var/log/memgraph
    command: ["--init-file=/tmp/init/init.cypherl", "--data-recovery-on-startup=true"]
    healthcheck:
      test: ["CMD-SHELL", "echo 'RETURN 0;' | mgconsole || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s

  mage_s2:
    image: memgraph/memgraph-mage:latest
    environment:
      - MEMGRAPH_MANAGEMENT_PORT=13011
      - MEMGRAPH_USER=user
      - MEMGRAPH_PASSWORD=user
    ports:
      - "7689:7687"  # Bolt protocol
      - "13013:13011"  # Management port
    volumes:
      - ./init_secondary.cypherl:/tmp/init/init.cypherl:ro
      - mg_lib3:/var/lib/memgraph
      - mg_log3:/var/log/memgraph
    command: ["--init-file=/tmp/init/init.cypherl", "--data-recovery-on-startup=true"]
    healthcheck:
      test: ["CMD-SHELL", "echo 'RETURN 0;' | mgconsole || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s

  lab:
    image: memgraph/lab:latest
    ports:
      - "3000:3000"
    depends_on:
      - mage
    environment:
      - QUICK_CONNECT_MG_HOST=mage_p
      - QUICK_CONNECT_MG_PORT=7687
