name: prometheus_node_exporter

services:

  node_exporter:
    # https://github.com/prometheus/node_exporter
    # image: prom/node-exporter:latest
    image: quay.io/prometheus/node-exporter:latest
    restart: always
    command:
      # - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    environment:
      - TZ=UTC
    # ports:
    #   - ${NODE_EXPORTER_PORT:-9100}:9100
    network_mode: host
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
      # - "/:/host:ro,rslave"
    pid: host
