
services:

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - PORTAINER_ADMIN_PASSWORD_EXPIRY=24h
      - PORTAINER_ENABLE_EDGE_COMPUTE=true
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # for docker swarm
      # - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
    ports:
      # webui
      - "9000:9000"
      # edge agent (optional)
      - "8000:8000"
    networks:
      - portainer_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.local`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

  # to manage remote Docker hosts
  portainer-agent:
    profiles:
      - agent
    image: portainer/agent:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - AGENT_CLUSTER_ADDR=portainer-agent
      - AGENT_PORT=9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
    ports:
      - "9001:9001"
    networks:
      - portainer_network

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

networks:
  portainer_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
