name: portainer-simple

services:

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - "${PORTAINER_HTTP_PORT:-9000}:9000"   # webui HTTP
      # - "${PORTAINER_HTTPS_PORT:-9443}:9443"  # webui HTTPS
      # - "${PORTAINER_EDGE_AGENT_PORT:-8000}:8000"  # edge agent (optional)
    environment:
      - TZ=UTC
      - PORTAINER_ENABLE_EDGE_COMPUTE=true
    volumes:
      - portainer_data:/data
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /var/run/podman/podman.sock:/var/run/docker.sock
      # - /var/run/user/1000/podman/podman.sock:/var/run/docker.sock
    userns_mode: "keep-id:uid=1000,gid=1000"
    networks:
      - agent_network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # to access host via host.docker.internal

volumes:
  portainer_data:

networks:
  agent_network:
    external: true
    name: portainer_agent_default
