
name: portainer-simple

services:

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "9000:9000"  # webui HTTP
      # - "9443:9443"  # webui HTTPS
      # - "9001:9001"  # agent HTTP
      # - "9444:9444"  # agent HTTPS
    volumes:
      - ./data:/data
      # - /run/docker.sock:/run/docker.sock
      # - /run/podman/podman.sock:/var/run/docker.sock
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock
    userns_mode: "keep-id:uid=1000,gid=1000"
